name: flutter_social_textfield
description: TextEditingController and RichText / TextSpan builder with hashtag, url and mention detection with Regular Expressions. Also with tap support.
version: 0.1.2
homepage: https://github.com/dreampowder/flutter_social_textfield

environment:
  sdk: ">=3.0.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
